#!/usr/bin/env python3
"""Regenerate input-manifest.json from the files the builders actually read.

The manifest pins the sha256 of every source file that influences a generated
resource, so `verify_inputs.py` can prove a rebuild that diverges is the code's
fault and not the data's.

It is generated, never hand-edited, and it discovers inputs by calling the
BUILDERS' OWN `locate_inputs()` functions rather than re-implementing their
globs. That matters: the manifest previously listed 16 files while 43 more sat
in sources/ unpinned, including everything behind icd-10-cm 2024 and three of
the five ICD-10-PCS releases — so `make verify-inputs` reported "all verified"
while ignoring the inputs behind half the output. Importing the discovery logic
makes that drift impossible.

Which years count comes from the same ICD10_YEARS / ICD10PCS_YEARS the Makefile
passes to the builders, so a release you do not build is not pinned.

Usage:
  uv run scripts/terminology-mapping/update_manifest.py
  uv run scripts/terminology-mapping/update_manifest.py --icd10cm-years 2016 2024
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import paths  # noqa: E402

TERM = Path(__file__).resolve().parent
sys.path.insert(0, str(TERM / "terminology" / "icd10cm"))
sys.path.insert(0, str(TERM / "terminology" / "icd10pcs"))

import build_icd10cm_codesystem as icd10cm  # noqa: E402
import build_icd10pcs_codesystem as icd10pcs  # noqa: E402

MANIFEST = TERM / "input-manifest.json"

DEFAULT_ICD10CM_YEARS = ["2016", "2017", "2018", "2019", "2024"]
DEFAULT_ICD10PCS_YEARS = ["2016", "2018", "2019", "2020"]

# ICD-9-CM has no locate_inputs(): the builder takes explicit --source /
# --proc-source paths and globs the CMS descriptions next to them.
ICD9_DIR = "icd9/2012"
ICD9_FILES = ["Dtab12.rtf", "Ptab12.RTF",
              "CMS29_DESC_LONG_DX.101111.txt", "CMS29_DESC_LONG_SG.txt"]


def entry(base, path):
    return {
        "path": str(path.relative_to(base)),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "bytes": path.stat().st_size,
    }


def collect(base, icd10cm_years, icd10pcs_years):
    files, missing = [], []

    for name in ICD9_FILES:
        path = base / ICD9_DIR / name
        (files if path.is_file() else missing).append(
            entry(base, path) if path.is_file() else f"{ICD9_DIR}/{name}")

    for year in icd10cm_years:
        year_dir = base / "icd10cm" / year
        if not year_dir.is_dir():
            missing.append(f"icd10cm/{year}/")
            continue
        order, tabular = icd10cm.locate_inputs(year_dir, year)
        files += [entry(base, p) for p in (order, tabular) if p]

    for year in icd10pcs_years:
        year_dir = base / "icd10pcs" / year
        if not year_dir.is_dir():
            missing.append(f"icd10pcs/{year}/")
            continue
        order, tables, index = icd10pcs.locate_inputs(year_dir, year)
        files += [entry(base, p) for p in (order, tables, index) if p]

    return files, missing


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base-dir", type=Path, default=paths.SOURCES)
    ap.add_argument("--icd10cm-years", nargs="+", default=DEFAULT_ICD10CM_YEARS)
    ap.add_argument("--icd10pcs-years", nargs="+", default=DEFAULT_ICD10PCS_YEARS)
    args = ap.parse_args()

    existing = json.loads(MANIFEST.read_text()) if MANIFEST.is_file() else {}
    files, missing = collect(args.base_dir, args.icd10cm_years, args.icd10pcs_years)

    manifest = {
        "description": existing.get(
            "description",
            "sha256 of every raw ICD source file that influences a generated "
            "resource. Generated by update_manifest.py; do not hand-edit."),
        "sources": existing.get("sources", {}),
        "note": ("Generated by update_manifest.py from the builders' own "
                 "locate_inputs(). Covers ICD-10-CM "
                 f"{', '.join(args.icd10cm_years)} and ICD-10-PCS "
                 f"{', '.join(args.icd10pcs_years)}. Index, drug and neoplasm "
                 "XMLs shipped in the CMS zips are deliberately NOT pinned: no "
                 "builder reads them, so they cannot influence output."),
        "files": sorted(files, key=lambda f: f["path"]),
        "mimic_data": existing.get("mimic_data", {}),
    }
    MANIFEST.write_text(json.dumps(manifest, indent=1) + "\n")

    was = len(existing.get("files", []))
    print(f"wrote {MANIFEST.name}: {was} -> {len(files)} files pinned")
    for f in manifest["files"]:
        print(f"  {f['bytes']:>12,}  {f['path']}")
    if missing:
        print(f"\nWARNING: {len(missing)} expected input(s) absent, not pinned:")
        for m in missing:
            print(f"  {m}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
