# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kindlab.fhir.mimic
canonical: http://mimic.mit.edu/fhir/mimic
name: MIMIC
title: MIMIC Implementation Guide
status: draft
version: 1.3.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: Draft
publisher:
  name: KinD Lab
  url: http://fhir.kindlab.sickkids.ca

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Guidance:
    General: guidance.html
    Terminology: terminology-guide.html
    Applications: applications.html
    Tutorials: tutorials.html
    Roadmap: roadmap.html
  Subsets:
    Microbiology: microbiology-background.html
    Medication: medication-background.html
    ED: ed-subset.html
    ICU: icu-subset.html
  Mappings: 
    MIMIC-IV: mimic-fhir-mappings.html
    MIMIC-ED: mimic-ed-fhir-mappings.html
  Artifacts:
    Profiles: artifacts.html
    Terminology: terminology.html
  Examples: index.html
  Downloads: downloads.html
  Change Log: changelog.html
